---
name: Image Cleanup
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Alpine Mainline, Alpine Stable, Debian Mainline, Debian Stable]
    types: [completed]
jobs:
  cleanup:
    name: Delete untagged NGINX Unprivileged Docker images on the Amazon ECR Public Gallery and the GitHub Container Registry
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
    steps:
      - name: Check out the codebase
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Delete untagged NGINX Unprivileged Docker images on the Amazon ECR Public Gallery
        run: |
          .github/workflows/scripts/delete-untagged-amazon-public-ecr-images.sh

      - name: Delete untagged NGINX Unprivileged Docker images on the GitHub Container Registry
        uses: stumpylog/image-cleaner-action/untagged@48f1aa2111ae929cea4a0e056045f7de0e1b2618 # v0.10.0
        with:
          is_org: true
          owner: nginxinc
          package_name: nginx-unprivileged
          do_delete: true
          token: ${{ secrets.GITHUB_TOKEN }}
